### ISSUE TITLE
Whatsapp Business API in botman

### ISSUE THREAD

**Issue by dafner** [botman/botman#853] opened 2018-08-02 02:40 UTC
As a Botman user developing bots for facebook messenger, I wanted to know if it is planned to add whatsapp to the Botman platform?
Especially considering that the way to communicate with the api is very similar to facebook messenger.

Here I leave the links of whatsapp Business APIs

https://developers.facebook.com/docs/whatsapp
https://developers.facebook.com/docs/whatsapp/api/webhooks
https://developers.facebook.com/docs/whatsapp/api/webhooks/inbound

Thank you very much for any information.

**Comment by christophrumpel** [comment] 2018-08-02 06:49
Hey @dafner , from what I know they have a kind of "early access" right now where people can apply for a business account. So I don't think you can use it right away now? I am sure it is planned to add  a Whatsapp driver. Maybe I can start even today if @mpociot is up for it?

**Comment by mpociot** [comment] 2018-08-02 06:52
I’m already looking into it. But the docker setup makes a BotMan integration a bit harder to manage as every phone number is connected to one particular docker instance

**Comment by christophrumpel** [comment] 2018-08-02 06:53
oh really? damn!

**Comment by mpociot** [comment] 2018-08-02 14:59
So we can make this work by simply configuring the WhatsApp client host and make api requests to this client. 
I’m currently waiting to get my hands on the api

**Comment by dafner** [comment] 2018-08-02 15:07
It would really be very interesting to be able to see whatsapp integration in this framework in the near future.

Thank you very much for the development of this framework and its continuous updates

**Comment by stefandanaita** [comment] 2018-09-03 22:42
Hi @mpociot! Is this still on your roadmap? 😄Thanks!

**Comment by mpociot** [comment] 2018-10-04 14:02
I'm closing this right now, as my WhatsApp Business API application got rejected. If I can get my hands on the API to try it out, I'll make sure to reopen this.

**Closed by mpociot** 2018-10-04 14:02 UTC

**Comment by holtkamp** [comment] 2019-10-09 12:17
It seems Facebook prefers to work with partners like Twilio for this: 

https://www.twilio.com/docs/sms/whatsapp/api

**Comment by andresfabianguerrero** [comment] 2020-05-04 19:02
Hello @mpociot , is botman already integrated with whatsapp (business)?

**Comment by rajendrap123** [comment] 2020-06-07 03:21
Hello @mpociot  Any update on this? waiting for this.

**Comment by sherpaxit** [comment] 2020-07-19 14:21
In 360dialog you can use the whatsapp direct API ..  Is there any chance to make a driver for Whatsapp Direct API ?? https://developers.facebook.com/docs/whatsapp/api/messages
Thanks!!!!

**Comment by eugenefvdm** [comment] 2021-03-06 11:08
I'm subscribing to this topic. I want to use Twilio's WhatsApp Business API and pay for whatever, but for now it's unclear to me if Botman's Twilio integration actually works with their WhatsApp API. The current Twilio integration appears to be telephone related. Does any know?

FYI there is a beautiful and simple article here on how to get Laravel and the WhatsApp API working:
https://www.twilio.com/blog/build-whatsapp-chatbot-twilio-whatsapp-api-php-laravel

Now if I could combine that with Botman I could take our customer services to the next level.

**Comment by dimonise** [comment] 2021-03-15 10:44
Hello. I would like to know - there is a solution for Whatsapp?

**Comment by eugenefvdm** [comment] 2021-03-15 11:01
> there is a solution for Whatsapp?

No, there is not a solution for WhatsApp. I will explain later. For now, you do this:

1. Try using a WhatsApp partner like 360:

https://github.com/botman/botman/issues/1174

2. Try using this person's code who "made it work" with Twilio:

https://github.com/botman/botman/issues/1228
refers to 
https://github.com/jilenloa/botman-sample/tree/master/app/BotManDrivers

I tried but couldn't.

The reason for this difficulty is not a Botman problem. It's a WhatsApp Business API problem.

See WhatsApp got late to the API party and they are overly protective on who uses their API. As a mere end-user you would probably struggle to get your number approved - so WhatsApp prefers to work through 3rd parties.

You'll also see comment by Marcel about closing the issue due to approval problems. So WhatsApp is not friendly enough for Botman.

**Comment by modasto** [comment] 2021-06-23 18:23
> > there is a solution for Whatsapp?
> 
> No, there is not a solution for WhatsApp. I will explain later. For now, you do this:
> 
> 1. Try using a WhatsApp partner like 360:
> 
> #1174
> 
> 1. Try using this person's code who "made it work" with Twilio:
> 
> #1228
> refers to
> https://github.com/jilenloa/botman-sample/tree/master/app/BotManDrivers
> 
> I tried but couldn't.
> 
> The reason for this difficulty is not a Botman problem. It's a WhatsApp Business API problem.
> 
> See WhatsApp got late to the API party and they are overly protective on who uses their API. As a mere end-user you would probably struggle to get your number approved - so WhatsApp prefers to work through 3rd parties.
> 
> You'll also see comment by Marcel about closing the issue due to approval problems. So WhatsApp is not friendly enough for Botman.

Any one got this to work?

**Comment by rafaellannes** [comment] 2021-07-17 04:28
I would like to know too.

I developed a bot using botman and it was very good, but there was a need to migrate it to whatsapp. I had to start again using other approaches.

It would be great if the botman could work.

**Comment by modasto** [comment] 2021-07-17 12:01
> I would like to know too.
> 
> I developed a bot using botman and it was very good, but there was a need to migrate it to whatsapp. I had to start again using other approaches.
> 
> It would be great if the botman could work.

I did manage to get it to work with Twilio

**Comment by jawizie** [comment] 2021-12-29 08:14
> > I would like to know too.
> > I developed a bot using botman and it was very good, but there was a need to migrate it to whatsapp. I had to start again using other approaches.
> > It would be great if the botman could work.
> 
> I did manage to get it to work with Twilio

How did you do it?

**Comment by legreco** [comment] 2022-02-17 01:23
Hello everyone,
any updates about this topic?

**Comment by irwan-runtuwene** [comment] 2022-09-06 00:47
I've build custom driver for whatsapp business API. It's not fully functional yet just for text and button reply. 
https://github.com/irwan-runtuwene/driver-whatsapp
Feel free to modify to suit your needs

**Comment by c-myers1** [comment] 2022-11-23 09:08
@irwan-runtuwene : thank you for this. I see it's for the on-premises API, what changes are needed to get it working for Cloud API?

**Comment by mohapinkepane** [comment] 2025-01-29 14:08
For anyone looking for Botman WhatsApp Cloud API driver in 2025 :  https://github.com/mohapinkepane/driver-whatsapp-cloud

**Comment by legreco** [comment] 2025-01-29 15:09
I can confirm. Currently using @mohapinkepane Whatsapp Cloud API driver in one of my projects. It works flawlessly
