### ISSUE TITLE
mpociot/slack-client installing failed

### ISSUE THREAD

**Issue by e2haining** [botman/botman#680] opened 2018-01-07 18:34 UTC
- BotMan Version: 2.1.5
- PHP Version:7.2.0
- Messaging Service(s):
- Cache Driver:

### Description:
botman/driver-slack is installed OK .
composer require botman/driver-slack

But I need The Realtime API , so I tried to install  mpociot/slack-client,
using composer require mpociot/slack-client.
But I got following error

```
Using version ^1.0 for mpociot/slack-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mpociot/slack-client ^1.0 -> satisfiable by mpociot/slack-client[1.0].
    - Conclusion: remove evenement/evenement v2.1.0
    - Conclusion: don't install evenement/evenement v2.1.0
    - mpociot/slack-client 1.0 requires evenement/evenement ~3.0 -> satisfiable by evenement/evenement[3.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[3.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[v3.0.1, v2.1.0].
    - Installation request for evenement/evenement (locked at v2.1.0) -> satisfiable by evenement/evenement[v2.1.0].

```
### Steps To Reproduce:

**Comment by e2haining** [comment] 2018-01-08 05:27
clue/stdio-react is required by  botman/tinker
and it requires react/stream:^0.4.2 which requires evenement/evenement 2.1.0
is there any solutions?

**Comment by wagonza** [comment] 2018-01-11 14:03
On a clean installation of BotMan Studio it fails on installing the Slack driver 

```
php artisan botman:install-driver slack
Installing driver "Slack"
Using version ^2.0 for botman/driver-slack

./composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for botman/driver-slack ^2.0 -> satisfiable by botman/driver-slack[2.0.0].
    - botman/driver-slack 2.0.0 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Error installing driver "Slack"
```

**Comment by ajmariduena** [comment] 2018-01-11 16:41
One way to make this works is to install SlackDriver package before botman, Another fix is to install SlackDriver 1.0 instead of 2.0.

Hope it helps.

**Comment by mpociot** [comment] 2018-01-11 22:08
Duplicate of #668 
Please use slack-driver 1.* in the meantime

**Closed by mpociot** 2018-01-11 22:08 UTC

**Comment by Iyata** [comment] 2019-03-06 11:58
Hi,
I have Slack Driver 1.0 installed.
I try:
composer require mpociot/slack-client 1.0

Error:
Problem 1
- The requested package react/stream (locked at v1.1.0, required as ^0.7.5) is satisfiable by react/stream[v1.1.0] but these conflict with your requirements or minimum-stability.
Problem 2
- Installation request for mpociot/slack-client 1.0 -> satisfiable by mpociot/slack-client[1.0].
- Conclusion: remove react/event-loop v1.1.0
- Conclusion: don't install react/event-loop v1.1.0
- mpociot/slack-client 1.0 requires react/event-loop ^0.4.1 -> satisfiable by react/event-loop[0.4.x-dev, v0.4.1, v0.4.2, v0.4.3].
- Can only install one of: react/event-loop[0.4.x-dev, v1.1.0].
- Can only install one of: react/event-loop[v0.4.1, v1.1.0].
- Can only install one of: react/event-loop[v0.4.2, v1.1.0].
- Can only install one of: react/event-loop[v0.4.3, v1.1.0].
- Installation request for react/event-loop (locked at v1.1.0) -> satisfiable by react/event-loop[v1.1.0].

Please help.
